// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smhzfghaqydjwtwdkifz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaHpmZ2hhcXlkand0d2RraWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NjU2NjksImV4cCI6MjA4MzU0MTY2OX0.ag0MmojUu2AYiKkEymDxsfSyyqtkcsIEaUIw-qGaoQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});